Debian package for solitaire

diff --git a/qsolitaire/debian/postinst b/qsolitaire/debian/postinst
--- a/qsolitaire/debian/postinst
+++ b/qsolitaire/debian/postinst
@@ -1,10 +1,42 @@
-#!/bin/sh -e
+#!/bin/sh
+# postinst script for qtmoko
+#
+# see: dh_installdeb(1)
 
-gtk-update-icon-cache -f /usr/share/icons/hicolor
+set -e
 
-#oldversion="$2"
-#if [ -z "$oldversion" ]; then
-#	  maemo-select-menu-location qsolitaire.desktop 
-#fi
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+        # rescan .desktop files so that we appear on the list
+        . /opt/qtmoko/qpe.env
+        qcop QPE/DocAPI 'scanPath(QString,int)' /opt/qtmoko/apps/Applications 1
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 exit 0
